config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :pictures do
    member do
      put "like", to: "pictures#upvote"
    end
  end

  root "pictures#index"
  get 'mypictures' => 'pictures#mypictures'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true
    validates :image_file_name, presence: true


	acts_as_votable
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :find_picture, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pictures = Picture.all.order("created_at DESC")
	end

	def new
		@picture = current_user.pictures.build
	end

	def create
		@picture = current_user.pictures.build(picture_params)

		if @picture.save
			redirect_to @picture, notice: "Successfully created!"
		else
			render 'new'
		end
	end


	def edit
	end

	def update
		if @picture.update(picture_params)
			redirect_to @picture, notice: "Successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@picture.destroy
		redirect_to root_path		
	end

	def upvote
		@picture.upvote_by current_user
		redirect_to :back
	end

	def mypictures
		@pictures = current_user.pictures.order("created_at DESC")
	end

	private

		def picture_params
			params.require(:picture).permit(:title, :description, :image)
		end

		def find_picture
			@picture = Picture.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoMine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse">
  		<div class="container">
    		<div class="navbar-brand">
    			<%= link_to "Photo Mine", root_path %>
    		</div>


			<% if user_signed_in? %>
 				 <ul class="nav navbar-nav navbar-left">
				    <li>
				      <%= link_to 'New Pic', new_picture_path %>
				    </li>
				    <li>
				      <%= link_to 'My Pic', mypictures_path %>
				    </li>
				  </ul>
				  <ul class="nav navbar-nav navbar-right">
				    <li>
				      <%= link_to 'Settings', edit_user_registration_path %>
				    </li>
				    <li>
				      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
				    </li>
			  	  </ul>

	  	    <% else %>
	  	    	<ul class="nav navbar-nav navbar-left">
				    <li>
				      <%= link_to 'Sign up', new_user_registration_path %>
				    </li>
				    <li>
				      <%= link_to 'Sign in', new_user_session_path %>
				    </li>
				  </ul>
			<% end %>

  		</div>
	</nav>



	<div class="container">
  		<% flash.each do |name, msg| %>
    	<%= content_tag :div, msg, class: 'alert alert-info' %>
  		<% end %>
	</div>

	<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= simple_form_for @picture, html: { multipart: true } do |f| %>

  <% if @picture.errors.any? %>

    <div id="errors">
      <h2>
      	<%= pluralize(@picture.errors.count, "error") %>
      	prevented this Pic from saving
      </h2>
      
      <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-group">
  	<%= f.input :title, input_html: { class: 'form-control'} %>
  </div>
  
  <div class="form-group">
  	<%= f.input :description, input_html: { class: 'form-control'} %>
  </div>
  
  <%= f.button :submit, 'Submit' ,class: 'btn btn-info' %>

<% end %>

app/views/pictures/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Fix Pic!</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Right Now</strong>
          <%= image_tag @picture.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="col-md-12">
  <div class="transitions-enabled" id="pics">
    <% @pictures.each do |picture| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag picture.image.url), picture %>
        <h2>
          <%= link_to picture.title, picture %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/mypictures.html.erb
<div class="col-md-12">
  <div class="transitions-enabled" id="pics">
    <% @pictures.each do |picture| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag picture.image.url), picture %>
        <h2>
          <%= link_to picture.title, picture %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post your picture</h1>
      </div>
      <div class="panel-body">
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="row" id="pic_show">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel heading pic_image">
        <%= image_tag @picture.image.url %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @picture.title %>
        </h1>
        <p>
          <%= @picture.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
             by <%= @picture.user.email %>
            </p>
          </br>
          </div>
          <div class="col md-6">
            <div class="btn-group pull-right">
              <%= link_to like_picture_path(@picture), method: :put, class: 'btn btn-default' do %>
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <%= @picture.get_upvotes.size %>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to 'Fix Pic', edit_picture_path, class: "btn btn-info" %>
                <%= link_to 'Delete', picture_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>